version: "3"
services:
  web:
    build: .
    command: poetry run python3 django_project/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.development
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: "giaco-dev-user-dev"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "giaco-dev-db-dev"
    ports:
      - "5435:5432"
    volumes:
      - postgres_giaco_dev_data_dev:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"

volumes:
  postgres_giaco_dev_data_dev:
