version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_giaco_dev_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:6379"
      
volumes:
  postgres_giaco_dev_data:
